#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/postinst.pgsql  ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.pgsql
fi

case "$1" in

  remove)
    /usr/bin/yes | pip uninstall yotta
  ;;

  abort-install|purge|abort-deconfigure|abort-upgrade|failed-upgrade|upgrade)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

#DEBHELPER#

db_stop

exit 0
