#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/postinst.pgsql  ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.pgsql
fi

case "$1" in

  configure)
    echo "********************************************************************************"
    echo "*                                                                              *"
    echo "*  GCC ARM toolchain installed in /opt/gcc-arm-none-eabi                       *"
    echo "*                                                                              *"
    echo "********************************************************************************"
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

#DEBHELPER#

db_stop

exit 0
